### PR TITLE
src: add support for 10.16.0

### PR DESCRIPTION
**Pull request by helio-frota**

### CODE REVIEW

**Review by lholmquist — APPROVED** [review]

**Comment by helio-frota** [comment]
Same travis error as previous builds in other node versions...
`No IPv6 network detected`
This is the third time I "rebuild", so If that build don't pass I'll merge. :+1:

**Comment by lholmquist** [comment]
if it doesn't build and we merge,  will the automated tag creation thing work then?  doesn't it run the same thing?

**Comment by helio-frota** [comment]
Yes, but since this is a random error [that happened before](https://github.com/nodeshift/node-rpm/search?q=ipv6&type=Issues), we postpone that possibility to the automatic tag creation phase, like done before. :+1:

**Comment by helio-frota** [comment]
I'm going to build locally just to be sure :+1:

**Comment by helio-frota** [comment]
We have errors, and that time it is not related to IPv6 travis flaky issues.

```
No IPv6 network detected
[       OK ] InspectorSocketServerTest.BindsToIpV6 (0 ms)
[----------] 10 tests from InspectorSocketServerTest (148 ms total)

[----------] Global test environment tear-down
[==========] 80 tests from 10 test cases ran. (284 ms total)
[  PASSED  ] 80 tests.
  TOUCH d883b6bdbc96a3499341843e46133ca12cb65d67.intermediate
  ACTION _opt_app_root_src_rpmbuild_BUILD_node_v10_16_0_rh_deps_v8_gypfiles_v8_gyp_v8_torque_host_run_torque d883b6bdbc96a3499341843e46133ca12cb65d67.intermediate
  TOUCH 5e4aee5a7818a6cae7a12b78943bbe5da57d28f7.intermediate
  ACTION Generating inspector protocol sources from protocol json 5e4aee5a7818a6cae7a12b78943bbe5da57d28f7.intermediate
  TOUCH 9b807651be98a7e2db8c37689167d5bd945cb45e.intermediate
  ACTION Generating node protocol sources from protocol json 9b807651be98a7e2db8c37689167d5bd945cb45e.intermediate
=== release test-fs-copyfile-respect-permissions ===                          
Path: parallel/test-fs-copyfile-respect-permissions
assert.js:84
  throw new AssertionError(obj);
  ^

AssertionError [ERR_ASSERTION]: Missing expected exception (check).
    at Object.<anonymous> (/opt/app-root/src/rpmbuild/BUILD/node-v10.16.0-rh/test/parallel/test-fs-copyfile-respect-permissions.js:38:10)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
Command: out/Release/node /opt/app-root/src/rpmbuild/BUILD/node-v10.16.0-rh/test/parallel/test-fs-copyfile-respect-permissions.js
[05:13|% 100|+ 2468|-   1]: Done                                              
make[1]: *** [jstest] Error 1
make: *** [test] Error 2
error: Bad exit status from /var/tmp/rpm-tmp.2oXcuZ (%build)


RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.2oXcuZ (%build)
```

**Comment by danbev** [comment]
> Yes, but since this is a random error [that happened before](https://github.com/nodeshift/node-rpm/search?q=ipv6&type=Issues),

I don't think that is the actual error. That is just a warning from the log by the looks of it.

**Pull request merged**
