### PR TITLE
chore: update gcc version in specfile

### PR DESCRIPTION
**Pull request by yselkowitz**
@helio-frota please consider this in place of #170.

### CODE REVIEW

**Comment by helio-frota** [comment]
Dockerfile updated and build restarted.

**Comment by helio-frota** [comment]
@yselkowitz @danbev the build now shows now only a single missing package.

That is weird because I've added both:
https://github.com/nodeshift/node-rpm/commit/275fe87ed34ca8182a845cb312ad8a7fdec0f6c8

```
error: Failed build dependencies:
	devtoolset-7-gcc-g++ is needed by rhoar-nodejs-1:11.1.0-1.el7.centos.x86_64
```

**Comment by helio-frota** [comment]
Maybe we should use 

`yum install -y devtoolset-7 && \` 

instead 

`yum install -y devtoolset-7-gcc devtoolset-7-gcc-g++ && \`

I'm not sure.

**Comment by danbev** [comment]
@helio-frota I'm not exactly sure, I'd have to try this locally to see what is happening and what is missing. Can you try doing running it locally ?

**Comment by helio-frota** [comment]
I'm getting the same error when using only `devtoolset-7`

```
node-rpm v11.x-staging🔒 ✏️ 2 docker run -it -v ${PWD}/rpms:/opt/app-root/src/rpmbuild/RPMS bucharestgold/node-rpm 
Cloning into 'node-v11.1.0-rh'...
remote: Enumerating objects: 26, done.
remote: Counting objects: 100% (26/26), done.
remote: Compressing objects: 100% (23/23), done.
remote: Total 446447 (delta 16), reused 3 (delta 3), pack-reused 446421
Receiving objects: 100% (446447/446447), 416.04 MiB | 807.00 KiB/s, done.
Resolving deltas: 100% (325696/325696), done.
Note: checking out 'af6d26281f734dbbf1bf497103d1cb4b85a52b2e'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

Checking out files: 100% (30334/30334), done.
/opt/app-root/src/rpmbuild/SPECS/run.sh: line 12: [: ==: unary operator expected
error: Failed build dependencies:
	devtoolset-7-gcc-g++ is needed by rhoar-nodejs-1:11.1.0-1.el7.centos.x86_6
```

I'm going to remove that require statement to see what happens.

**Comment by helio-frota** [comment]
@yselkowitz @danbev the build is working locally after remove the require statement for 
`devtoolset-7-gcc-g++` . The build still running locally for 11.1.0 I'll wait to finish, then build again locally for 11.2.0 to be sure, then update upstream with the changes, then merge @yselkowitz PR.

**Comment by helio-frota** [comment]
@yselkowitz almost build finished locally we got another error:

```
  COPY Release/napi_binding.node
gyp info ok 
[05:30|% 100|+ 2449|-   0]: Done                                               
+ EOF
/var/tmp/rpm-tmp.Mj9v4L: line 57: EOF: command not found
error: Bad exit status from /var/tmp/rpm-tmp.Mj9v4L (%build)


RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.Mj9v4L (%build)
```

I have no idea, can this be something related to [this line](https://github.com/nodeshift/node-rpm/pull/173/commits/931cceede9e0e36aa0e3cb22ec5767d310f90fb0#diff-9b2d71b9964b34777f72bc4f23ab718aR184)?

**Comment by yselkowitz** [comment]
sorry for the typo it should gave been c++ not g++

**Comment by helio-frota** [comment]
@yselkowitz not a problem with the typo, but anyway the build will be broken after compile and run the all the tests. 

And that not seems to be related with removing the restriction inside nodejs.spec file.

**Comment by yselkowitz** [comment]
As for the EOF, check where it is found in the rh-nodejs8 specfile.

**Review by helio-frota — COMMENTED** [review]
Using travis build as feedback is faster than my local build.
Some code was pushed to 11x upstream, I'm going to merge this PR and then we 
can focus only on the next build error that arise.

**Comment by helio-frota** [comment]
we can continue here in case necessary: https://github.com/nodeshift/node-rpm/pull/175

**Pull request merged**
