### PR TITLE
src: add support for 10.15.1

### PR DESCRIPTION
**Pull request by helio-frota**

### CODE REVIEW

**Comment by helio-frota** [comment]
I'm going to restart the build I don't know about the error.

**Comment by helio-frota** [comment]
@danbev this error is not clear for me:
https://api.travis-ci.org/v3/job/486449043/log.txt
Can you take a look when you have a chance?
Thanks!

**Comment by danbev** [comment]
@helio-frota It's hard to inspect the actual cause of this issue just looking at the log on travis. If you run this locally that sound show us some more details.

**Comment by helio-frota** [comment]
@danbev you're right, I forgot the `SILENT` option. I'm Building locally :+1:

**Comment by helio-frota** [comment]
@danbev here the full log with `SILENT=false`:
[buillog.txt](https://github.com/nodeshift/node-rpm/files/2814313/buillog.txt)

**Comment by danbev** [comment]
It looks like we need a update the compiler version on the image. If you
take a look at the version used on the image and compare it to the version
specified in BUILDING.md these should match (or the version on the image
should be greater than the one specified in BUILDING.md).

ons 30 jan. 2019 kl. 21:27 skrev Helio Frota <notifications@github.com>:

**Comment by helio-frota** [comment]
I've changed to use the same 11x configuration and building locally to see if it works.

**Comment by helio-frota** [comment]
I'm going to merge.
This is the same case of weirdo tests on travis.
The build locally finished fine.

```
[##################] | extractTree: sill extractTree object-keys@1.0.12 -> /opt[0m[K

[K[?25hadded 101 packages in 2.726s
(node:20790) ExperimentalWarning: The fs.promises API is experimental
(node:22684) ExperimentalWarning: The fs.promises API is experimental
No IPv6 network detected
make[1]: *** [jstest] Error 1
make: *** [test] Error 2
error: Bad exit status from /var/tmp/rpm-tmp.8ZSUbY (%build)
    Bad exit status from /var/tmp/rpm-tmp.8ZSUbY (%build)
travis_time:end:21d8adf8:start=1548958656408906640,finish=1548962245311989192,duration=3588903082552
[0K[31;1mThe command "docker run -e SILENT=true -it -v ${PWD}/rpms:/opt/app-root/src/rpmbuild/RPMS bucharestgold/node-rpm" failed and exited with 1 during .[0m

Your build has been stopped.
```

**Pull request merged**
